# Generated by Django 4.1.7 on 2023-03-16 19:24

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('is_open', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('yelping_since', models.DateTimeField(blank=True, null=True)),
                ('useful', models.IntegerField(blank=True, null=True)),
                ('funny', models.IntegerField(blank=True, null=True)),
                ('cool', models.IntegerField(blank=True, null=True)),
                ('fans', models.IntegerField(blank=True, null=True)),
                ('average_stars', models.FloatField(blank=True, null=True)),
                ('compliment_hot', models.IntegerField(blank=True, null=True)),
                ('compliment_more', models.IntegerField(blank=True, null=True)),
                ('compliment_profile', models.IntegerField(blank=True, null=True)),
                ('compliment_cute', models.IntegerField(blank=True, null=True)),
                ('compliment_list', models.IntegerField(blank=True, null=True)),
                ('compliment_note', models.IntegerField(blank=True, null=True)),
                ('compliment_plain', models.IntegerField(blank=True, null=True)),
                ('compliment_cool', models.IntegerField(blank=True, null=True)),
                ('compliment_funny', models.IntegerField(blank=True, null=True)),
                ('compliment_writer', models.IntegerField(blank=True, null=True)),
                ('compliment_photos', models.IntegerField(blank=True, null=True)),
                ('friends', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('elite_years', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('tip_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('compliment_count', models.IntegerField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'tip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('useful', models.IntegerField(blank=True, null=True)),
                ('funny', models.IntegerField(blank=True, null=True)),
                ('cool', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('opening_time', models.TimeField(default=datetime.time(9, 30))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
            options={
                'db_table': 'hours',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
            options={
                'db_table': 'checkin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
            options={
                'db_table': 'attribute',
                'managed': True,
            },
        ),
    ]
